server:
  port: 8082

spring:
  datasource: # A서버에서 기동 및 포트를 개방한 H2
    url: jdbc:h2:tcp://localhost:9091/mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none